### ISSUE TITLE
Update React compatability

### ISSUE THREAD

**Issue by rosibaj** [oncojs/survivalplot#8]
When using survial plot in KF, Paule had some compatability issues with the latest version of React. 

- had to re-use `@oncojs/survivalplot` and make my own react-component based on the one provided by `@oncojs/survivalplot-react`
- the only thing needed is to use `import PropTypes from 'prop-types';` instead of `import { PropTypes } from 'react'`

Update the library to make this easier to use in future

**Comment by andricDu** [comment]
@rosibaj I've merged @cheapsteak 's PR, do you require publishing a new version to npm?

**Comment by rosibaj** [comment]
@cheapsteak Thanks for the update 🎉 !!
@andricDu That would be awesome if you could publish it!

**Comment by nyanofthemoon** [comment]
@andricDu Kindly let me know when the new npm version is published so that I can integrate.
